// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class ImagesRes {
  ImagesRes._();

  static const String PLUGIN_NAME = 'weather';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String CITY_BACKGROUND = 'images/city_background.jpg';
  static const String LOCATION_BACKGROUND = 'images/location_background.jpg';
}
